storage-provider: 'FileStorageProvider' # FileStorageProvider or S3StorageProvider
baseurl: 'https://something.example.com/%file%'

replace-blocks:
  0:
    search: '^DEEPSLATE_.*_ORE$' # regex
    replace: 'DEEPSLATE'
  1:
    search: '^(?!DEEPSLATE_).*_ORE$'
    replace: 'STONE'
  2:
    search: 'ANCIENT_DEBRIS'
    replace: 'NETHERRACK'
s3:
  auth:
    enabled: true
    accessKey: 'key'
    secretKey: 'secret'
  region: 'us-east-1'
  bucket: 'bucket'
  endpoint: 'https://s3.example.com'
