name: PublicSchematics
version: '${version}'
main: dev.badbird.publicschematics.PublicSchematics
api-version: 1.19
depend:
  - WorldEdit
commands:
  downloadschem:
    description: Download your current selection as a schematic
    usage: /downloadschem
    aliases: [ds]

permissions:
    downloadschem.use:
        description: Allows the player to download their current selection as a schematic
        default: true
